# Site
name: 'TechAbbi'
#description: 'TechAbbi | Blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'TechAbbi'
email: 'abidul.rmdn@gmail.com'
contact-formspree-endpoint: 'https://formspree.io/f/xeqwavgd'
mailchimp-list: 'https://medium.us2.list-manage.com/subscribe/post?u=6e2e48dbdcf3aa060e8b276da&amp;id=c56c8a29c4&amp;f_id=001658e0f0'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    abidul:
      name:           Abidul
      site:           https://abidul.dev
      avatar:         assets/images/avatar-abidul.jpg
      bio:            "Hi, I am Abbi/Abidul, the author of TechAbbi, the author of this blog. I hope you like it!"
      email:          abidul.rmdn@gmail.com
      twitter:        https://twitter.com/AbidulRamadan

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]